name: CICD workflow

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup .net Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x


      - name: Install dependencies
        run: dotnet restore ./pommes/pommes.csproj

      - name: Build project
        run: dotnet build ./pommes/pommes.csproj --configuration Release

      - name: Publish project
        run: dotnet publish ./pommes/pommes.csproj --configuration Release --output ./publish